name: C++ CI Pipeline

on:
  push:
    branches: 
    - main
    - parallel
  pull_request:
    branches: 
    - main
    - parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential doxygen

    - name: Build the project
      run: make

    - name: Run Doxygen
      run: doxygen Doxyfile

    - name: Clean build artifacts
      run: make clean